services:
  - type: web
    name: ruleflow-backend
    env: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: static_site
    name: ruleflow-frontend
    staticPublishPath: dist
    root: frontend
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_URL
        sync: false
