services:
  - type: web
    name: ruleflow-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: static_site
    name: ruleflow-frontend
    staticPublishPath: frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: VITE_API_URL
        sync: false
